### ISSUE TITLE
[FACTUAL-ERROR] Ludivine Dedonder & Dries Van Langenhove: Party Affiliation

### ISSUE THREAD

**Issue by nesnaj-blip** [Parliament-in-Data/Federal-Parliament-Scraper#46]
### Which session? / Welke legislatuur?

55ste legislatuur

### What entity types (e.g. member, meeting, party) does this affect? / Welke soorten entiteit(en) (e.g. Kamerleden, Partijen, Vergadering) worden door deze fout beïnvloed?

Kamerleden

### What specific entities are affected? / Welke specifieke entiteiten worden beïnvloed door deze fout?
*List the URLs of API routes if possible. Or specify the names of the party, member or the date of the meeting. / Geef de URLs die u gebruikt op, of specificeer de naam van de partij, het kamerlid of de datum van de vergadering die betrokken is.*

Ludivine Dedonder (is not a member of MR but of PS)
Dries Van Langenhove (is member of the vlaams belang fraction and not independent)

**Comment by laurensdeb** [comment]
Thanks for reporting these issues!

- The factual error with regards to Ludivine Dedonder has been resolved. (see 0983e10)
- As we use party affiliation (at election time) rather than fraction membership in the API, the party affiliation information on Dries Van Langenhove is considered correct. However this does highlight a need for fraction membership in the API which will be put on the roadmap. (see #47) 

As party affiliations and fraction memberships can even evolve over time which hasn't been accounted for in the API yet, we'll try to provide a proper solution for this at some point in the future.

**Comment by nesnaj-blip** [comment]
Thanks for clarifying and thank you also for creating this scraper. It has been a big help for me and I will off course credit your work when I publish something.
